# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: boom-boot.spec

# add or remove files that should be synced
files_to_sync:
    - boom-boot.spec
    - .packit.yaml

# format for upstream version tags
upstream_tag_template: "{version}"
# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: boom
# downstream (Fedora) RPM package name
downstream_package_name: boom-boot
