---
name: Boom CI
on: [push]
jobs:
  python-basic-tests:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Fedora deps
        run: >
          dnf -y install
          python3-dbus
          python3-pycodestyle
          python3-sphinx
          python3-coverage
          python3-pytest
          python-unversioned-command
          python3-toml
          bandit
      - name: Install Boom
        run: >
          sudo python3 setup.py install
      - name: Check PyCodestyle
        run: >
          pycodestyle boom
      - name: Run bandit
        run: >
          bandit -c bandit.toml -r boom
      - name: Run test suite
        run: >
          pytest -v
